<font size="3" color="brown">Author : UTSAV AWASTHI</font><br>
<font size="1" color="brown">About Me: http://iamawesome.com/ </font> <br>
Subscribe to my YouTube channel <a href="https://www.youtube.com/channel/UCJpp55YcP5swWj8TmIOd0OA/">here</a><br> 
For serious conversations related to career and jobs, follow me on <a href="https://www.linkedin.com/in/utsavawasthi/">LinkedIn</a><br>
For low-effort dank memes and one-liners, follow me on <a href="https://twitter.com/utsavsaidwhat">Twitter</a>

<div align="center">
    <font size = 3 color="orange" style="font-family: 'Comic Sans MS'">// ज्ञानं परमं बलम् //</font><br>
</div>
<img src = "https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" width="50%" height="50%">
<div align="center" id="contents"> <font size="5" color="orange"><b>PYTHON PROGRAMMING LANGUAGE</b></font> </div>

<div align="left"> <font size="4" color="red"><b>TABLE OF CONTENTS</b></font> </div>
<ol type="square">
    <li><a href="#regex">Regular Expressions</a></li>
    <li><a href="#numpy">NumPy</a></li>
    <li><a href="#pandas">Pandas</a></li>
    <li><a href="#mat">matplotlib.pyplot</a></li>
</ol>

<div align="left" id="regex"><a href="#contents"><font size="4" color="red"><b>REGULAR EXPRESSIONS</b></font></a></div>
<ol type="square">
    <li><a href="#regex_simple">Simple Matching</a></li>
    <li><a href="#regex_re">re module</a></li>
    <li><a href="#regex_wild">Wild Card Characters: Special Characters</a></li>
    <li><a href="#regex_rep">Repetitions</a></li>
    <li><a href="#regex_groups">Groups and Grouping</a></li>
    <li><a href="#regex_greedy">Greedy vs Non-Greedy Matching</a></li>
</ol>

Regular Expressions (or regex in short) are a powerful tool to find patterns in a text data. For example if we have a really big word document, given enough time (and motivation) a human can read the whole document and make a list of all emails and phone numbers mentioned anywhere in the document.<br>
With computers, you can do the same thing just by telling it what pattern it should look for. Like in Phone number the pattern could be any one of these XXXXXXXXXX or XXX XXX XXXX or XXXXX XXXXX etc. Or in case of emails it is SOME&#95;TEXT&#64;SOME&#95;TEXT.SOME&#95;TEXT 

<div align="left" id ="regex_simple"> <a href="#regex"><font size="3" color="black"><b>Simple Matching</b></font></a></div>

There are multiple string methods available by default, which you use to perform basic pattern matching<br>

In [2]:
#checking presence of a substring
my_string = "Hi! How are you?"
if "are" in my_string:
    print ("Present")
else:
    print ("Absent")

Present


In [3]:
#matching is case-sensitive
if "Are" in my_string:
    print ("Present")
else:
    print ("Absent")

Absent


As we have seen in Module 1, the "in" operator also works with lists, tubles, sets and dictionaries

In [4]:
#mystr.find(’am’, <start to search from index>, <end search at index>) - outputs "-1" if not found
print (my_string.find("are"))
print (my_string.find("Hi",1))
print (my_string.find("Hi",0,1))

8
-1
-1


In [5]:
#rfind() finds from back
print ("rfind example : ", my_string.rfind("are"))

rfind example :  8


In [6]:
#index is similar to find, but raises ValueError if not present.
print ("index example : ", my_string.index("are"))

index example :  8


In [7]:
#You can also check if a string starts or ends with a particular substring
print (my_string.startswith("H"))
print (my_string.endswith("!"))

True
False


The following methods return True if the string only contains characters of the appropiate type, False otherwise :<br>
<b>isalpha()</b> - alphabetic<br>
<b>isdigit()</b> - digits<br>
<b>isdecimal()</b> - float numbers, etc<br>
<b>isnumeric()</b> - similar, covers special chars like ½<br>
<b>isalnum()</b> - all of above<br>
<b>islower()</b> - contains only lowercase<br>
<b>isupper()</b> - contains only uppercase<br>
<b>isspace()</b> - contains only whitespace<br>

In [9]:
print ("Hello world!".isalpha()) 
print ("Helloworld".isalpha()) 

False
True


In [5]:
a = 5

def func1():
    global a
    a = 4

def func2(b,c):
    global a
    return a + b + c

b, c = 10 , 5
func1()
val = func2(1,2)

print (val)


7


In [8]:
#replace doesn't modify the string
my_string = "My Grade is D!"
print (my_string.replace("D!","A+!"))
print (my_string)

My Grade is A+!
My Grade is D!


In [ ]:
#You can use lstrip(), rstrip() or strip(). These are used to remove leading or trailing white spaces
my_string = "\tHow are you?   "
print (">"+my_string.strip()+"<")
#Again the string is not modified
print (">"+my_string+"<") 

In [ ]:
#split() can be used to split the line into list of words
my_string = "\tHow are\tyou?\t\t"
print (my_string.split())
print (my_string.split(" ")) #split by spaces
print (my_string.split("\t"))#split by tabs

<div align="left" id ="regex_re"> <a href="#regex"><font size="3" color="black"><b>re module</b></font></a></div>

Regular expressions are used to identify whether a pattern exists in a given sequence of characters (string) or not. They help in manipulating text data, which is often a pre-requisite for data science projects that involve text mining<br><br>
In Python, the "re" module provides the support for regular expressions. We will discuss few methods inside this module<br><br>

In [10]:
import re
pattern = r"Cookie" # r at the begining is called a raw string literal
sequence = "Cookie"
if re.match(pattern, sequence):
     print ("Match!")
else: print("Not a match!")

Match!


r at the begining is called a raw string literal. It changes how the string literal is interpreted. Such literals are stored as they appear. <br><br>
search ⇒ find something anywhere in the string and return a match object.<br>
match ⇒ find something at the beginning of the string and return a match object.

Both of them return a match object if something is found, otherwise "None"

In [11]:
# example code:
string_with_newlines = """something
someotherthing"""

import re

print (re.match('some', string_with_newlines)) # matches
print (re.match('someother', string_with_newlines)) # won't match
print (re.search('someother', string_with_newlines)) # finds something

<re.Match object; span=(0, 4), match='some'>
None
<re.Match object; span=(10, 19), match='someother'>


<b>group, start, end, and span</b>

In [12]:
r1 = re.search("a*b","fooaaabcde") #search occurance of "a", followed by anything, followed by "b"
print (r1)
print (r1.group())  # group returns string matched
print (r1.start())  # index of the match start
print (r1.end())    # index of the match end
print (r1.span())   # tuple of (start, end)

<re.Match object; span=(3, 7), match='aaab'>
aaab
3
7
(3, 7)


<div align="left" id ="regex_wild"> <a href="#regex"><font size="3" color="black"><b>Wild Card Characters: Special Characters</b></font></a></div>

Special characters are characters which do not match themselves as seen but actually have a special meaning when used in a regular expression.

The most widely used special characters are as listed below.

In [13]:
#. - A period. Matches any single character except newline character
print (re.search(r'Co.k.e', 'Cookie').group())

Cookie


In [14]:
#\w - Lowercase w. Matches any single letter, digit or underscore
print (re.search(r'Co\wk\we', 'Cookie').group())
#\W - Uppercase w. Matches any character not part of \w (lowercase w).
print (re.search(r'C\Wke', 'C@ke').group())

Cookie
C@ke


In [ ]:
#\s - Lowercase s. Matches a single whitespace character like: space, newline, tab, return. 
print (re.search(r'Eat\scake', 'Eat cake').group())
#\S - Uppercase s. Matches any character not part of \s (lowercase s).
print (re.search(r'Cook\Se', 'Cookie').group())

In [ ]:
#\t - Lowercase t. Matches tab.
print (re.search(r'Eat\tcake', 'Eat	cake').group())
#\n - Lowercase n. Matches newline.
#\r - Lowercase r. Matches return.

In [ ]:
#\d - Lowercase d. Matches decimal digit 0-9.
print (re.search(r'c\d\dkie', 'c08kie').group())

In [ ]:
#^ - Caret. Matches a pattern at the start of the string.
print (re.search(r'^Eat', 'Eat cake').group())

#$ - Matches a pattern at the end of string.
print (re.search(r'cake$', 'Eat cake').group())

In [ ]:
#[abc] - Matches a or b or c. The first occurance only
print (re.search(r'[abc]', 'abccdbc').group())
#[a-zA-Z0-9] - Matches any letter from (a to z) or (A to Z) or (0 to 9). 
#Characters that are not within a range can be matched by complementing the set. 
#If the first character of the set is ^, all the characters that are not in the set will be matched.

In [ ]:
print (re.search(r'Number: [0-6]', 'Number: 54').group())

# Matches any character except 5
print (re.search(r'Number: [^5]', 'Number: 03').group())

In [ ]:
#re.findall() finds all matches
print(re.findall("\d+","12 dogs,11 cats, 1 egg"))

In [ ]:
#re.sub substitutes one string for a pattern
re.sub('(blue|white|red)', 'black', 'blue socks and red shoes')

<div align="left" id ="regex_rep"> <a href="#regex"><font size="3" color="black"><b>Repetitions</b></font></a></div>

It becomes quite tedious if you are looking to find long patterns in a sequence. Fortunately, the re module handles repetitions using the following special characters:

In [ ]:
#+ - Checks for one or more characters to its left.
re.search(r'Co+kie', 'Cooookie').group()

In [ ]:
#* - Checks for zero or more characters to its left.
re.search(r'Ca*o*kie', 'Caokie').group()

In [ ]:
#? - Checks for exactly zero or one character to its left.
re.search(r'Colou?r', 'Color').group()

We can check for exact number of repetitions too

In [ ]:
#{x} - Repeat exactly x number of times.
#{x,} - Repeat at least x times or more.
#{x, y} - Repeat at least x times but no more than y times.
re.search(r'\d{9,10}', '09876543219').group()
#goes till only 1

<div align="left" id ="regex_groups"> <a href="#regex"><font size="3" color="black"><b>Groups and Grouping</b></font></a></div>

Now suppose when you're validating email addresses and want to check the user name and host separately. This is when the 'group' feature of regular expression comes in handy. It allows you to pick up parts of the matching text. The groups are seperated using parentheses i.e. ()

In [15]:
email_address = 'Please contact us at: support@citi.com'
match = re.search(r'([\w\.-]+)@([\w\.-]+)', email_address) 
if match: 
    print (match.group()) # The whole matched text 
    print (match.group(1)) # The username (group 1) 
    print (match.group(2)) # The host (group 2)

support@citi.com
support
citi.com


In [ ]:
#We can also group 'groups'

pat2 = "(\w+)@((\w+\.)+(com|org|net|edu))"
r2 = re.match(pat2,"finin@cs.umbc.edu")
print (r2.group(1))
print (r2.group(2))
print (r2.groups())

In [ ]:
#We can ‘label’ the groups as well and reference the matching parts by the labels
pat3 ="(?P<name>\w+)@(?P<host>(\w+\.)+(com|org|net|edu))"
r3 = re.match(pat3,"finin@cs.umbc.edu")
print (r3.group('name'))
print (r3.group('host'))

<div align="left" id ="regex_greedy"> <a href="#regex"><font size="3" color="black"><b>Greedy vs Non-Greedy Matching</b></font></a></div>


When a special character matches as much of the search sequence (string) as possible, it is said to be a "Greedy Match". It is the normal behavior of a regular expression but sometimes this behavior is not desired:

In [ ]:
heading  = r'<h1>TITLE</h1>'
re.match(r'<.*>', heading).group()

<div align="left" id="numpy"><a href="#contents"><font size="4" color="red"><b>NUMPY</b></font></a></div>
<ol type="square">
    <li><a href="#numpy_arrays">Arrays</a></li>
    <li><a href="#numpy_matrix">Matrix Operations</a></li>
    <li><a href="#numpy_index">Indexing and Slicing</a></li>
    <li><a href="#numpy_tricks">Some Tricks</a></li>
</ol>

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices. It has a large collection of high-level mathematical functions to operate on these arrays. Numpy is not a default pacakge in Python and you will need to install it first. Luckily it comes pre-installed in Anaconda<br>
You might ask why a seperate package/module for matrics. The answer is that all the algorithms in machine learning or Deep Learning or AI internally work their magic using matrices. So it is very important to have a module which has highly optimized mathematical operations on matrices

<div align="left" id ="numpy_arrays"> <a href="#numpy"><font size="3" color="black"><b>Arrays</b></font></a></div>
<br>
NumPy Array is a datatype defined inside numpy library, just like list is a datatype available by default. Computation with NumPy arrays is much faster than the native lists

In [2]:
import numpy as np

In [40]:
#Creating array with list of lists
#1D array
print ("1d : \n", np.array([1,2,3]))

1d : 
 [1 2 3]


In [8]:
#2D array
print ("2d : \n", np.array([[1,2,3],[4,5,6]])) #notice the list of lists

2d : 
 [[1 2 3]
 [4 5 6]]


In [19]:
#With arange() funciton
print (np.arange(10))  # like Python's range, but returns an array
print (np.arange( 10, 30, 5 )) #start, end, step

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]


In [20]:
# it accepts float arguments
print (np.arange( 0, 2, 0.3 )) 

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [4]:
#With rearranging
print (np.arange(6).reshape(3, 2)) #reshaping arange to a 3x2 array

[[0 1]
 [2 3]
 [4 5]]


In [12]:
#reshape is also a function
print (np.reshape([1,2,3,4,5,6], (3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [10]:
#an array of zeroes
print (np.zeros( (3,4) ))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
#a 3d array of ones
print (np.ones( (2,3,4), dtype=np.int16 ))  

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [33]:
#an identity matrix
print (np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#Certain attributes
a = np.arange(30).reshape(3, 5, 2) #3 arrays of dimension 5x2
print ("a :\n", a)
print ('Attribuites of a:\n')
print ("Shape:", a.shape)
print ("Dimensions:", a.ndim)
print ("itemsize:", a.itemsize) #Length of one array element in bytes
print ("Data type:", a.dtype)
print ("Size:", a.size) #number of elements
print ("Type:", type(a))

a :
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
Attribuites of a:

Shape: (3, 5, 2)
Dimensions: 3
itemsize: 4
Data type: int32
Size: 30
Type: <class 'numpy.ndarray'>


In [37]:
#You can specify the data type while creating arrays
a = np.array( [ [1,2], [3,4] ], dtype=complex )
print ("a: \n", a)
print ("a.dtype:", a.dtype)

a: 
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
a.dtype: complex128


In [12]:
import numpy as np
a = np.array([[7,8],[-3,5]])
b = a.reshape(-1,1)
print(b)
print(a)

[[ 7]
 [ 8]
 [-3]
 [ 5]]
[[ 7  8]
 [-3  5]]


In [41]:
#Using linspace you can create evenly spaced numbers over a specified interval
print (np.linspace( 0, 2, 9 ))                 # 9 numbers from 0 to 2

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [44]:
a = np.linspace( 0, 2*np.pi, 100 ) #numpy has pi defined inside of it
print (a)
print (np.sin(a))

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [49]:
#You can create random distributions too
np.random.normal(0.0, 1.0, (2, 2, 2))

array([[[ 0.63733712,  0.74882044],
        [ 0.75546438, -1.62353118]],

       [[ 0.50155206, -0.4269697 ],
        [-0.66449425, -0.94112065]]])

In [46]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution

In [ ]:
help(np.random.normal)

If you haven't figured out already, numpy arrays are MUTABLE

In [52]:
#Simple assignments make no copy of array objects or of their data because numpy arrays are mutable too
a = np.arange(12)
b = a            # no new object is created
print ("b is a?", b is a)           # a and b are two names for the same ndarray object
print(id(a), id(b))

b is a? True
2245484629568 2245484629568


In [ ]:
print ("Shape before:", a.shape)
b.shape = 3,4    # changes the shape of a
print ("Shape before:", a.shape)

In [ ]:
print(a)

<div align="left" id ="numpy_matrix"> <a href="#numpy"><font size="3" color="black"><b>Matrix Operations</b></font></a></div>

NumPy supports all major matrix operations

In [23]:
a = np.arange(6).reshape(2, 3)
b = np.arange(2,8).reshape(3, 2)
c = np.arange(6).reshape(3, 2)
print ("a:\n", a)
print ("b:\n", b)
print ("c:\n", c)

a:
 [[0 1 2]
 [3 4 5]]
b:
 [[2 3]
 [4 5]
 [6 7]]
c:
 [[0 1]
 [2 3]
 [4 5]]


In [54]:
b+c #try b-c also

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [55]:
#Dot Product
np.dot(a,b) #try b,a too 
#or a.dot(b)

array([[16, 19],
       [52, 64]])

In [56]:
np.dot(b,a)

array([[ 9, 14, 19],
       [15, 24, 33],
       [21, 34, 47]])

In [57]:
#Transpose
np.transpose(a)
#or simple a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [58]:
from numpy.linalg import inv
inv(a[0:2,0:2])

array([[-1.33333333,  0.33333333],
       [ 1.        ,  0.        ]])

In [ ]:
np.dot(inv(a[0:2,0:2]),a[0:2,0:2])

In [59]:
#Functions get applied to all the elements
a*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [60]:
a**2

array([[ 0,  1,  4],
       [ 9, 16, 25]], dtype=int32)

In [61]:
a<3

array([[ True,  True,  True],
       [False, False, False]])

In [62]:
np.mean(a) #min, max etc are there too

2.5

In [63]:
#You can take column sums(or min/max etc) OR row sums too
b.sum(axis=1)   #1 means along rows

array([ 5,  9, 13])

In [64]:
b.mean(axis=0)   #0 means along column

array([4., 5.])

In [65]:
# returns the array, flattened
b.ravel()  

array([2, 3, 4, 5, 6, 7])

In [66]:
#You can stack the arrays
a = np.zeros((2,2))
b = np.ones((2,2))
print (np.vstack((a,b)))
print (np.hstack((a,b)))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


<div align="left" id ="numpy_index"> <a href="#numpy"><font size="3" color="black"><b>Indexing and Slicing</b></font></a></div>

Remember numbering/indexing starts from 0 in Python

In [67]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
#first row
print ("First row of a: ", a[0, :])# : means everything

First row of a:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [71]:
#second columns
print ("Second column of a: ", a[:, 2] )

Second column of a:  [ 2  7 12]


In [ ]:
#slicing works too
print (a[1:3, 2:4]) #From row index 1 to row index 3-1, column index 2 to column index 4-1 

In [ ]:
#You can use indexing/slicing to assign values
a[1:3, 2:4] = -1
a

In [ ]:
#Using steps
a = np.arange(10)**3
print (a)

In [24]:
a[:6:2] = -1000  #change every second element till index 5 (i.e. 6-1)
print (a)

[[-1000 -1000 -1000]
 [    3     4     5]]


In [25]:
#You can use slicing to create new arrays
a = np.arange(12).reshape(2,3,2) #two arrays of 3x2
b = a[:,:,:]    #3 dimensions three columns 
print (id(a), id(b))
print (a)
print (b)

1550791608800 1550791630480
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
#Or you can use copy() method
b = a.copy()    #3 dimensions three columns 
print (id(a), id(b))

<div align="left" id ="numpy_tricks"> <a href="#numpy"><font size="3" color="black"><b>Some Tricks</b></font></a></div>

Replacing elements based on a condition

In [ ]:
a = np.arange(12).reshape((3,4))
print ("a:\n", a)

In [ ]:
b = a>6 #Here a>6 creates a boolean array and then that is use as index below
print ("b:\n", b)

In [ ]:
a[b] = -1
print ("a finally :\n", a)

Here a>6 creates a boolean array and then that is use to index 

In [ ]:
#pearson correlation
data = np.random.normal(size=[100, 5]) #100 rows, 5 columns
print(np.corrcoef(data.T))

In [ ]:
#solving equations ax = b
a = np.array([[1,2],[3,-4]])
b = np.array([2,16])
print (np.linalg.solve(a,b))

<div align="left" id="pandas"><a href="#contents"><font size="4" color="red"><b>PANDAS</b></font></a></div>
<ol type="square">
    <li><a href="#pandas_df">Introduction to Dataframes</a></li>
    <li><a href="#pandas_manu">Manipulating Dataframes</a></li>
    <li><a href="#pandas_stats">Statistics with Dataframes</a></li>
</ol>

Pandas is a high-level data manipulation tool. It is built on the Numpy package and its key data structure is called the DataFrame (along with one more known as series)

<div align="left" id ="pandas_df"> <a href="#pandas"><font size="3" color="black"><b>Introduction to Dataframes</b></font></a></div>

In [27]:
import pandas as pd

In [28]:
#You can create dataframes with list of lists, where each list is one row in the data
data = [['ABC', -3.5, 0.01], ['ABC', -2.3, 0.12], 
        ['DEF', None, 0.03], ['DEF', 3.7, 0.01], 
        ['GHI', 0.04, 0.43], ['GHI', -0.1, 0.67]]
df = pd.DataFrame(data, columns=['gene', 'log2FC', 'pval'])
df

gene  log2FC  pval
0  ABC   -3.50  0.01
1  ABC   -2.30  0.12
2  DEF     NaN  0.03
3  DEF    3.70  0.01
4  GHI    0.04  0.43
5  GHI   -0.10  0.67

In [33]:
#or you can create using dictionaries, where keys are column names and values are the values in the column
pd.DataFrame({'name':['Anil', 'John', 'Ali'], 'age':[5,6,7]})

name  age
0  Anil    5
1  John    6
2   Ali    7

But mostly we will be reading data from files. Here is how you read a csv file

In [34]:
#Let's first set the working directory
import os
os.chdir(r"C:\Users\utsav.awasthi\Documents\Personal\Python for Data Analytics")

#Now load the dataset
iris = pd.read_csv("iris.csv")
print (type(iris))
iris.head()

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\utsav.awasthi\\Documents\\Personal\\Python for Data Analytics'

read_csv() allows mutiple options like skipping first n rows/columns, define delimiter. As Thor says, let's do 'get help' :P

In [ ]:
help(pd.read_csv)

pd.read_excel and pd.read_sas are also supported

Here are some key things you should immediately do after importing a data set
<ol>
    <li>Check <b>shape</b> of the data i.e. #rows and #columns using df.shape</li>
    <li>Check <b>data type</b> of each column using df.info()</li>
    <li>Check <b>uniqueness</b> of the data i.e. ensure the data is unique at the primary keys' level. e.g for students data, check if the data is unique at roll_no and class_std or not, or customer data being unique at cust_id level using df.shape, df[['pk1','pk2']].drop_duplicates().shape</li>
    <li>Check <b>frequency</b> of key columns - like months, dates, etc. This will ensure you have complete data and not missing out some key information using df.col.value_counts(dropna=False)</li>
    <li>Check number of <b>null</b> values in each column using df.isna().sum()</li>
    <li>Some <b>basic stats</b> of each column using df.describe()</li>
    <li>Finally analyze some <b>random sample</b> of the data using df.sample(100), if you want to be extra sure. You can export sample to using df.sample(100).to_csv('sample.csv')</li>
</ol>

In [35]:
#Shape of the data
iris.shape 

NameError: name 'iris' is not defined

In [ ]:
#Data type - 'object' means its a non-number(i.e. not int/float) type column e.g. string 
iris.info()

In [ ]:
#ensuring data is unique at primary key(s) level
iris.shape, iris[['Id']].drop_duplicates().shape

In [ ]:
#frequency of some key columns
iris.Species.value_counts(dropna=False)

If you do not use "dropna = False" above, the frequency for null values in the column will not be shown

In [ ]:
#count of nulls in each column
iris.isna().sum()

In [ ]:
#Some Basic stats
iris.describe()

The above code gave descriptive statistics on numerical columns only. If you want the same for text columns, use the code below

In [ ]:
iris.describe(include=['O'])

In [ ]:
#Viewing data
iris.sample(10) 

You can use iris.tail() or iris head() if you want to see top of bottom rows only

In [ ]:
iris.tail(10)

<b>Slicing Dataframes using "iloc"</b><br>
Indexing and slicing works pretty much the same way as python lists - remember lst[a:b:c] ?. Just that here you need to provide a,b,c to slice index for both rows and columns. Let's see some examples

In [ ]:
iris.head()

In [ ]:
#gives everything
iris.iloc[:,:]

In [ ]:
#taking out the value at row index = 3, and column index = 3
iris.iloc[3,3]

In [ ]:
#taking out the values at row index between 0 and 2, and column index between 0 and 2
iris.iloc[0:3,0:3]

In [ ]:
#taking out the values at row index between 0 and 2, and column index between 0 and 2, 
#while skipping 1 row and column
iris.iloc[0:3:2,0:3:2]

<b>A better way of slicing Dataframes using "loc"</b><br>
For "iloc" you need to provide the location or index of columns or rows. That becomes troublesome if have a huge dataset with many rows/columns and you do not know the index of a particular row or column that you want. For example in case of banking data you might have thousands of rows or columns, finding the index of lets say 'sales' column is hard. <br><br>
So what can you do? You can use 'loc' and just ask pandas to display rows which satisfy particular condition(s) and also specify the columns by their names(i.e. not with index) within a list

In [ ]:
iris.loc[iris.Species == 'Iris-setosa', ['SepalLengthCm','SepalWidthCm','Species']].head()

You can specify multiple conditions on row selection using ampersand "&" and pipe "|"

In [ ]:
iris.loc[(iris.Species == 'Iris-setosa') & 
         (iris.SepalWidthCm >= 3.1), ['SepalLengthCm','SepalWidthCm','Species']].head()

Notice pandas labels the rows by default (see the very first column without any column name). That serves as the row name. It is NOT the index of rows, while it does look like it. Generally you will be using row names with 'loc' and will only use conditions on rows to filter data. Still here is one example of how it works

In [ ]:
#will print rows with names 1 to 4, NOT index 1 to 3 which happens in case of iloc
iris.loc[1:4,["Species","SepalWidthCm"]]

Here is a code which shows you the difference between 'loc' and 'iloc' in using row names. Notice how 'loc' above printed rows 1 to 4 because it prints all row names mentioned, but in case of 'iloc' below , it does not print the row at index 4

In [ ]:
iris.iloc[1:4,0:2]

Just do yourself a favor and avoid iloc

In [ ]:
#Getting column names
print (iris.columns)
print (type(iris.columns)) #Pandas data series is similar to lists in Python

<b>Ways to get specific columns</b>

In [ ]:
#prints column as series. Using head() to show only few values
iris.Species.head()

In [ ]:
#another similar way. This is a preferred way
iris['Species'].head()

In [ ]:
#following prints the column as a dataframe. Notice the two square brackets
iris[['Species']].head()

In [ ]:
#The above method can be used to print multiple columns 
iris[['Species', 'SepalWidthCm']].head()

In [ ]:
#same example as above using loc
iris.loc[:, ['Species', 'SepalWidthCm']].head()

<div align="left" id ="pandas_manu"> <a href="#pandas"><font size="3" color="black"><b>Manipulating Dataframes</b></font></a></div>

While working with any dataset, a good practice is to convert all the column names to either upper or lower case to avoid any error due to Case-sensitive nature of Python

In [ ]:
iris.columns

In [ ]:
iris.columns = iris.columns.str.upper()
iris.head()

In [ ]:
#You can rename columns by using 'rename' method and specifiying old and new names in a dictionary 
#and also what is it that you are renaming - columns or rows
iris.rename({'PETALLENGTHCM':'PETALLENGTHCM_NEW',
             'PETALWIDTHCM':'PETALWIDTHCM_NEW'},axis = 'columns').head()

In [ ]:
#Let's see if iris dataset is changed or not
iris.head()

Wait what?! Why didn't it rename but during print it showed new names? Answer: Any method in pandas generally does not make changes to the original dataset and only prints the output. You will need to store the output in a separate variable.

In [ ]:
iris = iris.rename({'PETALLENGTHCM':'PETALLENGTHCM_NEW','PETALWIDTHCM':'PETALWIDTHCM_NEW'},axis = 'columns')
iris.head()

Or (a less preferred way) you can use an option called "inplace = True" which is available in most pandas methods to enforce changes in the dataset during the use of a method. For example

In [ ]:
iris.rename({'SEPALLENGTHCM':'SEPALLENGTHCM_NEW','SEPALWIDTHCM':'SEPALWIDTHCM_NEW'},
            axis = 'columns',inplace = True)
iris.head()

Let's revert back to original names. You can rename columns like this also, but it is not preferred if you have many columns in the data

In [ ]:
iris.columns = ['ID','SEPALLENGTHCM','SEPALWIDTHCM','PETALLENGTHCM','PETALWIDTHCM','SPECIES']
iris.head()

In [ ]:
#if you want to sort the values for which you are getting frequency
iris.PETALLENGTHCM.value_counts(dropna=False).sort_index(ascending=False)

In [ ]:
#if you want to sort by frequency
iris.PETALLENGTHCM.value_counts(dropna=False).sort_values(ascending=False)

In [ ]:
iris = iris.sort_values(by=['ID'], ascending = [False])
# or you could have used below code
#iris.sort_values(by=['ID'], ascending = [True], inplace=True)
iris.head()

In [ ]:
#You can also sort by multiple columns. 
#Specify the columns in 'by' option 
#Speficy the sort order in 'ascending' option
iris = iris.sort_values(by=['PETALLENGTHCM', 'PETALWIDTHCM'], ascending = [False, True])
iris.head()

Adding columns

In [ ]:
#Adding a new column with a static value
iris['dummy'] = 1

#Addng a new column using some calculation on other columns
iris['SEPALLENGTHCM_SQ'] = iris['SEPALLENGTHCM'] * iris['SEPALLENGTHCM']
iris['LENGTH_AVG'] = (iris['SEPALLENGTHCM'] + iris['PETALLENGTHCM'])/2
iris['WIDTH_AVG'] = (iris['SEPALWIDTHCM'] + iris['PETALWIDTHCM'])/2

iris.head()

In [ ]:
#Adding columns basis some condition - basically pandas's if-else version
iris['new'] = 3
iris.loc[iris.SPECIES=='Iris-setosa', 'new'] = 1
iris.loc[iris.SPECIES=='Iris-virginica', 'new'] = 2
iris.head()

In [ ]:
#You can create cross-tabs between two columns too
pd.crosstab(iris.SPECIES, iris.new)

reset_index() converts outputs like above to dataframe. Notice the difference

In [ ]:
pd.crosstab(iris.SPECIES, iris.new).reset_index()

Dropping Columns

In [ ]:
iris = iris.drop(['dummy', 'new'], axis = 'columns')
iris.head()

Stacking two separate dataframes can be done using append() or concat()

In [ ]:
df1 = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'))
print(df1)
print()
print(df2)

In [ ]:
df1.append(df2, ignore_index = True)
#If you do not ignore index, pandas will save the original indexes from the two datasets

In [ ]:
#Stacking up side by side
pd.concat([df1,df2.rename(columns={'A':'C', 'B':'D'})],axis='columns') 

<b>SQL joins in pandas</b>

In [ ]:
new = pd.DataFrame([['Iris-virginica', 'IV'],['Iris-setosa', 'IS']], columns = ['Flowers', 'ShortForm'])
new

In [ ]:
iris.SPECIES.unique()

In [ ]:
#inner join 
temp1 = iris.merge(right = new, #what you want to merge
          how = 'inner', #how you want to merge i.e. type of join 
          left_on = ['SPECIES'], #join columns from left table
          right_on = ['Flowers'] #join columns from right table
          )
temp1.head()

In [ ]:
print(temp1.shape)
temp1.ShortForm.value_counts(dropna=False)

In [ ]:
#left join 
temp2 = iris.merge(right = new, #what you want to merge
          how = 'left', #how you want to merge i.e. type of join 
          left_on = ['SPECIES'], #join columns from left table
          right_on = ['Flowers'] #join columns from right table
          )
temp2.head()

In [ ]:
print(temp2.shape)
temp2.ShortForm.value_counts(dropna=False)

<div align="left" id ="pandas_stats"> <a href="#pandas"><font size="3" color="black"><b>Statistics with Dataframes</b></font></a></div>

You can apply certain functions on whole dataset by columns - like min(), max(), std(), mean(), nunique() etc. For Example

In [ ]:
iris.sum()

In [ ]:
iris.nunique()

You can get specific percentiles using 'quantile()'

In [ ]:
iris.quantile([0.0, 0.01, 0.50, 0.99, 1.0])

You can calculate correlations between numerical columns using corr()

In [ ]:
iris.corr()

Missing value Treament

In [ ]:
#Missing Value Treatment
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                    [3, 4, np.nan, 1],
                    [np.nan, np.nan, np.nan, 5],
                    [np.nan, 3, np.nan, 4]],
                    columns=list('ABCD'))
#Missing values in pandas are represented by NaN
df

In [ ]:
#Fill nulls with some value
df.fillna(0) #this doesn't replace df

In [ ]:
#or just drop all rows with missing
df.dropna()

<b> groupby() </b><br>
One of the most important utility in pandas is it's groupby() function, which allows you to aggregate information

In [ ]:
#Aggregation for all columns
iris.groupby(['SPECIES']).sum().reset_index()

In [ ]:
#Aggregation for specific columns
iris.groupby(['SPECIES'])['LENGTH_AVG','WIDTH_AVG'].sum().reset_index()

In [ ]:
#more than one aggregation 
iris.groupby(['SPECIES'])['LENGTH_AVG','WIDTH_AVG'].agg(['min','max', 'mean']).reset_index()

In [ ]:
#different aggregation for different columns
iris.groupby(['SPECIES']).agg({'LENGTH_AVG':'min', 'WIDTH_AVG':'max'}).reset_index()

In [ ]:
#Get unique values in a column
iris.SPECIES.unique()

In [ ]:
#Get number of unique values in a column
iris.SPECIES.nunique()

<div align="left" id="mat"><a href="#contents"><font size="4" color="red"><b>MATPLOTLIB.PYPLOT</b></font></a></div>
<ol type="square">
    <li><a href="#mat_basic">Basic Plotting</a></li>
    <li><a href="#mat_mult">Multiple plots</a></li>
    <li><a href="#mat_pix">Plotting Pixels</a></li>
</ol>

Matplotlib is a plotting library for the Python programming language and its numerical mathematics extension NumPy. matplotlib.pyplot is a collection of command style functions that make matplotlib work like MATLAB. Each pyplot function makes some change to a figure: e.g., creates a figure, creates a plotting area in a figure, plots some lines in a plotting area, decorates the plot with labels, etc

<div align="left" id ="mat_basic"> <a href="#mat"><font size="3" color="black"><b>Basic Plotting</b></font></a></div>

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot([1, 2, 3, 4], [1, 4, 9, 16])
plt.ylabel('some numbers')
plt.show() #You always need to use show() at the end

In [ ]:
plt.plot([1, 2, 3, 4], [1, 4, 9, 16], 'ro') #ro => r = red, 0 = points
plt.ylabel('some numbers')
plt.show() #You always need to use show() at the end

In [ ]:
# evenly sampled time at 200ms intervals
t = np.arange(0., 5., 0.2)

# red dashes, blue squares and green triangles
plt.plot(t, t, 'r--', t, t**2, 'bs', t, t**3, 'g^') #red dashes, blue squares, green triangles
plt.show()

In [ ]:
#Histogram
mu, sigma = 100, 15
x = mu + sigma*np.random.randn(10000)
plt.hist(x, bins=100, facecolor='orange')  #try changing value of bins parameter
plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.grid(True)
plt.show()

<div align="left" id ="mat_mult"> <a href="#mat"><font size="3" color="black"><b>Multiple Plots</b></font></a></div>

In [ ]:
x = np.linspace(0.0, 2*np.pi, 100)
_sin = np.sin(x)
_cos = np.cos(x)

plt.subplot(2, 1, 1)
plt.plot(x, _sin, 'y*', linewidth = 1)
plt.title('A tale of 2 subplots')
plt.ylabel('sin curve')

plt.subplot(2, 1, 2)
plt.plot(x, _cos, 'r--')
plt.xlabel('x')
plt.ylabel('cos curve')

plt.show()

<div align="left" id ="mat_pix"> <a href="#mat"><font size="3" color="black"><b>Plotting Pixels</b></font></a></div>

In [ ]:
data = np.random.random(size=(3, 3))
print(data)
plt.imshow(data, interpolation='nearest')
plt.xticks(np.arange(0.0, 2.5, 1), np.arange(0.5, 2, 0.5))
plt.yticks(np.arange(2, -0.5, -1), np.arange(0.5, 2, 0.5))
plt.title('The value of pixels refer to the color')
plt.show()

We encourage you to explore plot() function <a href="https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html">here</a>

<font size = 10 color="green">"</font><br>
<div align = center> 
    <font size = 5 color="green" style="font-family: 'Comic Sans MS'">Pass on what you have learned</font><br>
</div>
<div align = right> 
    <font size = 10 color="green"t>"</font><br>
</div>
<img align = "right" src = "https://orig00.deviantart.net/ff5e/f/2013/102/4/4/yoda_by_valval-d61g9rh.png" width="20%" height="20%">